// Mocks generated by Mockito 5.4.4 from annotations
// in start/test/domain/load_chat_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:start/domain/entities/chat_entity.dart' as _i2;
import 'package:start/domain/usecases/loadchat/load_chat_usecase.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChatEntity_0 extends _i1.SmartFake implements _i2.ChatEntity {
  _FakeChatEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LoadChatUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadChatUsecase extends _i1.Mock implements _i3.LoadChatUsecase {
  MockLoadChatUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ChatEntity> loadChatByUserId(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadChatByChatPartnerId,
          [id],
        ),
        returnValue: _i4.Future<_i2.ChatEntity>.value(_FakeChatEntity_0(
          this,
          Invocation.method(
            #loadChatByChatPartnerId,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.ChatEntity>);
}
