// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdVUj7bupKj4kpO4jwiKyjfJw7_F1JZbM',
    appId: '1:563851166700:web:ada74079a62b3dc704b6c9',
    messagingSenderId: '563851166700',
    projectId: 'simplechatapp-977fa',
    authDomain: 'simplechatapp-977fa.firebaseapp.com',
    storageBucket: 'simplechatapp-977fa.appspot.com',
    measurementId: 'G-ZS891E5VN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgrrFZwvAT1MsWK7u2e-I-vupI6-CyPYQ',
    appId: '1:563851166700:android:1d5259652bc912e304b6c9',
    messagingSenderId: '563851166700',
    projectId: 'simplechatapp-977fa',
    storageBucket: 'simplechatapp-977fa.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdVUj7bupKj4kpO4jwiKyjfJw7_F1JZbM',
    appId: '1:563851166700:web:7bd309ae9ce6347804b6c9',
    messagingSenderId: '563851166700',
    projectId: 'simplechatapp-977fa',
    authDomain: 'simplechatapp-977fa.firebaseapp.com',
    storageBucket: 'simplechatapp-977fa.appspot.com',
    measurementId: 'G-465V70TJYJ',
  );
}
